#!/usr/bin/env sh
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
    echo "You can't commit directly to main branch"
    exit 1
fi

echo "Husky -- Running pre-commit Lint"
npm run lint

echo "Husky -- Running pre-commit build"
npm run build
